import type { MeetEvent, DateEvent } from "./types";

export const NEXT_MEET_DATE = new Date("2026-07-05T07:00:00+07:00");
export const NEXT_MEET_NAME = "BISAC Invitational 2026";
export const NEXT_MEET_DETAIL = "Patana Sports Complex · Bangkok · Warm-up 7:00 AM";

export const meets: MeetEvent[] = [
  {
    id: "m1",
    month: "Mar",
    day: 15,
    name: "Opening Triangular Meet",
    location: "ISB Pool · Bangkok",
    status: "past",
    type: "meet",
  },
  {
    id: "m2",
    month: "Apr",
    day: 2,
    name: "NIST Dual Meet",
    location: "NIST Pool · Bangkok",
    status: "past",
    type: "meet",
  },
  {
    id: "m3",
    month: "Apr",
    day: 27,
    name: "Team Time Trials",
    location: "ISB Pool · All lanes",
    status: "past",
    type: "trial",
  },
  {
    id: "m4",
    month: "May",
    day: 18,
    name: "RIS Dual Meet",
    location: "RIS Aquatic Center · Bangkok",
    status: "past",
    type: "meet",
  },
  {
    id: "m5",
    month: "Jun",
    day: 1,
    name: "SEASAC Divisionals",
    location: "Bangkok Prep · Bangkok",
    status: "past",
    type: "championship",
    isChampionship: true,
  },
  {
    id: "m6",
    month: "Jun",
    day: 14,
    name: "NIST Dual Meet",
    location: "ISB Pool · Bangkok",
    status: "past",
    type: "meet",
  },
  {
    id: "m7",
    month: "Jul",
    day: 5,
    name: "BISAC Invitational",
    location: "Patana Sports Complex · Bangkok",
    status: "next",
    type: "meet",
  },
  {
    id: "m8",
    month: "Jul",
    day: 12,
    name: "Team Time Trials",
    location: "ISB Pool · All lanes",
    status: "upcoming",
    type: "trial",
  },
  {
    id: "m9",
    month: "Aug",
    day: 10,
    name: "End-of-Season Championship",
    location: "TBD",
    status: "upcoming",
    type: "championship",
    isChampionship: true,
  },
  {
    id: "m10",
    month: "Sep",
    day: 8,
    name: "Tryouts — Season 2026–27",
    location: "ISB Pool · Bangkok",
    status: "upcoming",
    type: "tryout",
  },
];

export const dates: DateEvent[] = [
  {
    id: "d1",
    month: "Jul",
    day: 4,
    name: "Team Pasta Party",
    detail: "ISB Cafeteria · 6:00 PM",
    type: "party",
  },
  {
    id: "d2",
    month: "Aug",
    day: 3,
    name: "Dues Deadline — Term 1",
    detail: "Via school admin portal",
    type: "payment",
  },
  {
    id: "d3",
    month: "Aug",
    day: 15,
    name: "Team Photo Day",
    detail: "ISB Pool Deck · 8:00 AM",
    type: "admin",
  },
  {
    id: "d4",
    month: "Aug",
    day: 22,
    name: "Season Awards Banquet",
    detail: "ISB Main Hall · 6:30 PM",
    type: "ceremony",
  },
  {
    id: "d5",
    month: "Sep",
    day: 1,
    name: "Dues Deadline — Term 2",
    detail: "Via school admin portal",
    type: "payment",
  },
  {
    id: "d6",
    month: "Sep",
    day: 20,
    name: "Welcome Back Pool Party",
    detail: "ISB Pool · 5:00 PM",
    type: "party",
  },
  {
    id: "d7",
    month: "Oct",
    day: 10,
    name: "Uniform Collection Deadline",
    detail: "Athletics Office",
    type: "admin",
  },
  {
    id: "d8",
    month: "Dec",
    day: 5,
    name: "End-of-Year Celebration",
    detail: "ISB Main Hall · 7:00 PM",
    type: "ceremony",
  },
];
