// src/lib/mockSwimmerProfiles.ts
//
// Personal info for the Swimmer Profile page (§3.B), extracted from the
// 2025-2026 multi-meet results report. Distinct from mockRoster.ts's
// placeholder roster (v6 §4) — these ages/genders/grad years are the real
// values printed on the report, not estimates. Reconcile the two mock
// sources before wiring either to Neon.

import type { SwimmerProfile } from './types';

export const mockSwimmerProfiles: SwimmerProfile[] = [
  {
    id: 'akasya-ayturk',
    firstName: 'Akasya',
    lastName: 'Ayturk',
    gender: 'Female',
    age: 10,
    gradYear: null,
    section: 'Elementary',
  },
  {
    id: 'yu-bo-chen',
    firstName: 'Yu',
    lastName: 'Bo Chen',
    gender: 'Male',
    age: 14,
    gradYear: 2029,
    section: 'High School',
  },
  {
    id: 'nattakit-choochaisengrat',
    firstName: 'Nattakit',
    lastName: 'Choochaisengrat',
    gender: 'Male',
    age: 15,
    gradYear: 2028,
    section: 'High School',
  },
  {
    id: 'matilde-cissna',
    firstName: 'Matilde',
    lastName: 'Cissna',
    gender: 'Female',
    age: 15,
    gradYear: 2028,
    section: 'High School',
  },
  {
    id: 'yunxi-gao',
    firstName: 'Yunxi',
    lastName: 'Gao',
    gender: 'Male',
    age: 7,
    gradYear: null,
    section: 'Elementary',
  },
  {
    id: 'ran-guo',
    firstName: 'Ran',
    lastName: 'Guo',
    gender: 'Female',
    age: 16,
    gradYear: 2027,
    section: 'High School',
  },
  {
    id: 'nanon-hanphanpong',
    firstName: 'Nanon',
    lastName: 'Hanphanpong',
    gender: 'Male',
    age: 13,
    gradYear: null,
    section: 'Middle School',
  },
  {
    id: 'pornnapa-khangrang',
    firstName: 'Pornnapa',
    lastName: 'Khangrang',
    gender: 'Female',
    age: 15,
    gradYear: 2029,
    section: 'High School',
  },
  {
    id: 'sion-kim',
    firstName: 'Sion',
    lastName: 'Kim',
    gender: 'Female',
    age: 16,
    gradYear: 2027,
    section: 'High School',
  },
  {
    id: 'varidrada-kithen',
    firstName: 'Varidrada',
    lastName: 'Kithen',
    gender: 'Female',
    age: 14,
    gradYear: 2029,
    section: 'High School',
  },
  {
    id: 'soo-yeon-kwon',
    firstName: 'Soo',
    lastName: 'Yeon Kwon',
    gender: 'Female',
    age: 16,
    gradYear: 2028,
    section: 'High School',
  },
  {
    id: 'trevin-laduke',
    firstName: 'Trevin',
    lastName: 'LaDuke',
    gender: 'Male',
    age: 13,
    gradYear: null,
    section: 'Middle School',
  },
  {
    id: 'abigail-leighton',
    firstName: 'Abigail',
    lastName: 'Leighton',
    gender: 'Female',
    age: 14,
    gradYear: null,
    section: 'High School',
  },
  {
    id: 'eleanor-leighton',
    firstName: 'Eleanor',
    lastName: 'Leighton',
    gender: 'Female',
    age: 15,
    gradYear: 2028,
    section: 'High School',
  },
  {
    id: 'wenxi-li',
    firstName: 'Wenxi',
    lastName: 'Li',
    gender: 'Female',
    age: 11,
    gradYear: null,
    section: 'Middle School',
  },
  {
    id: 'arthas-limsakulwattana',
    firstName: 'Arthas',
    lastName: 'Limsakulwattana',
    gender: 'Male',
    age: 9,
    gradYear: null,
    section: 'Elementary',
  },
  {
    id: 'laphon-manosuthisan',
    firstName: 'Laphon',
    lastName: 'Manosuthisan',
    gender: 'Male',
    age: 15,
    gradYear: 2028,
    section: 'High School',
  },
  {
    id: 'erica-medyarova',
    firstName: 'Erica',
    lastName: 'Medyarova',
    gender: 'Female',
    age: 15,
    gradYear: 2028,
    section: 'High School',
  },
  {
    id: 'palathip-panmai',
    firstName: 'Palathip',
    lastName: 'Panmai',
    gender: 'Male',
    age: 11,
    gradYear: null,
    section: 'Middle School',
  },
  {
    id: 'ploynapas-pholsuwanchai',
    firstName: 'Ploynapas',
    lastName: 'Pholsuwanchai',
    gender: 'Female',
    age: 11,
    gradYear: null,
    section: 'Middle School',
  },
  {
    id: 'thitibhorn-pronpanompong',
    firstName: 'Thitibhorn',
    lastName: 'Pronpanompong',
    gender: 'Female',
    age: 11,
    gradYear: null,
    section: 'Middle School',
  },
  {
    id: 'tiarn-sripongtanakul',
    firstName: 'Tiarn',
    lastName: 'Sripongtanakul',
    gender: 'Female',
    age: 16,
    gradYear: 2028,
    section: 'High School',
  },
  {
    id: 'tyler-srisumrid',
    firstName: 'Tyler',
    lastName: 'Srisumrid',
    gender: 'Male',
    age: 12,
    gradYear: null,
    section: 'Middle School',
  },
  {
    id: 'virunpat-sriyanuwatkul',
    firstName: 'Virunpat',
    lastName: 'Sriyanuwatkul',
    gender: 'Female',
    age: 16,
    gradYear: 2027,
    section: 'High School',
  },
  {
    id: 'kanyapak-tamonut',
    firstName: 'Kanyapak',
    lastName: 'Tamonut',
    gender: 'Female',
    age: 13,
    gradYear: null,
    section: 'Middle School',
  },
  {
    id: 'pattadon-tamonut',
    firstName: 'Pattadon',
    lastName: 'Tamonut',
    gender: 'Male',
    age: 10,
    gradYear: null,
    section: 'Elementary',
  },
  {
    id: 'abhikhun-tanchanpongs',
    firstName: 'Abhikhun',
    lastName: 'Tanchanpongs',
    gender: 'Male',
    age: 16,
    gradYear: 2027,
    section: 'High School',
  },
  {
    id: 'punyapat-thepnumsommanus',
    firstName: 'Punyapat',
    lastName: 'Thepnumsommanus',
    gender: 'Male',
    age: 17,
    gradYear: 2026,
    section: 'High School',
  },
  {
    id: 'narisara-tiranatvitayakul',
    firstName: 'Narisara',
    lastName: 'Tiranatvitayakul',
    gender: 'Female',
    age: 12,
    gradYear: null,
    section: 'Middle School',
  },
  {
    id: 'techid-tongviseskul',
    firstName: 'Techid',
    lastName: 'Tongviseskul',
    gender: 'Male',
    age: 17,
    gradYear: 2026,
    section: 'High School',
  },
  {
    id: 'peeravich-uea-amonvanish',
    firstName: 'Peeravich',
    lastName: 'Uea-amonvanish',
    gender: 'Male',
    age: 11,
    gradYear: null,
    section: 'Middle School',
  },
  {
    id: 'andrew-vitayakul',
    firstName: 'Andrew',
    lastName: 'Vitayakul',
    gender: 'Male',
    age: 13,
    gradYear: null,
    section: 'Middle School',
  },
  {
    id: 'bhat-wongtiraporn',
    firstName: 'Bhat',
    lastName: 'Wongtiraporn',
    gender: 'Male',
    age: 14,
    gradYear: 2028,
    section: 'High School',
  },
  {
    id: 'wenran-xie',
    firstName: 'Wenran',
    lastName: 'Xie',
    gender: 'Female',
    age: 12,
    gradYear: null,
    section: 'Middle School',
  },
  {
    id: 'vincent-yodpijit',
    firstName: 'Vincent',
    lastName: 'Yodpijit',
    gender: 'Male',
    age: 10,
    gradYear: null,
    section: 'Elementary',
  },
  {
    id: 'qingzhi-zhang',
    firstName: 'Qingzhi',
    lastName: 'Zhang',
    gender: 'Female',
    age: 8,
    gradYear: null,
    section: 'Elementary',
  },
];
