// src/lib/mockSwimmerProfiles.ts
//
// Personal info for the Swimmer Profile page (§3.B), extracted from the
// 2025-2026 multi-meet results report. Distinct from mockRoster.ts's
// placeholder roster (v6 §4) — these ages/genders/grad years are the real
// values printed on the report, not estimates. Reconcile the two mock
// sources before wiring either to Neon.

import type { SwimmerProfile } from './types';

export const mockSwimmerProfiles: SwimmerProfile[] = [
  {
    id: 'akasya-ayturk',
    name: 'Akasya Ayturk',
    gender: 'Female',
    age: 10,
    gradYear: null,
    section: 'Elementary',
  },
  {
    id: 'yu-bo-chen',
    name: 'Yu Bo Chen',
    gender: 'Male',
    age: 14,
    gradYear: 2029,
    section: 'High School',
  },
  {
    id: 'nattakit-choochaisengrat',
    name: 'Nattakit Choochaisengrat',
    gender: 'Male',
    age: 15,
    gradYear: 2028,
    section: 'High School',
  },
  {
    id: 'matilde-cissna',
    name: 'Matilde Cissna',
    gender: 'Female',
    age: 15,
    gradYear: 2028,
    section: 'High School',
  },
  {
    id: 'yunxi-gao',
    name: 'Yunxi Gao',
    gender: 'Male',
    age: 7,
    gradYear: null,
    section: 'Elementary',
  },
  {
    id: 'ran-guo',
    name: 'Ran Guo',
    gender: 'Female',
    age: 16,
    gradYear: 2027,
    section: 'High School',
  },
  {
    id: 'nanon-hanphanpong',
    name: 'Nanon Hanphanpong',
    gender: 'Male',
    age: 13,
    gradYear: null,
    section: 'Middle School',
  },
  {
    id: 'pornnapa-khangrang',
    name: 'Pornnapa Khangrang',
    gender: 'Female',
    age: 15,
    gradYear: 2029,
    section: 'High School',
  },
  {
    id: 'sion-kim',
    name: 'Sion Kim',
    gender: 'Female',
    age: 16,
    gradYear: 2027,
    section: 'High School',
  },
  {
    id: 'varidrada-kithen',
    name: 'Varidrada Kithen',
    gender: 'Female',
    age: 14,
    gradYear: 2029,
    section: 'High School',
  },
  {
    id: 'soo-yeon-kwon',
    name: 'Soo Yeon Kwon',
    gender: 'Female',
    age: 16,
    gradYear: 2028,
    section: 'High School',
  },
  {
    id: 'trevin-laduke',
    name: 'Trevin LaDuke',
    gender: 'Male',
    age: 13,
    gradYear: null,
    section: 'Middle School',
  },
  {
    id: 'abigail-leighton',
    name: 'Abigail Leighton',
    gender: 'Female',
    age: 14,
    gradYear: null,
    section: 'High School',
  },
  {
    id: 'eleanor-leighton',
    name: 'Eleanor Leighton',
    gender: 'Female',
    age: 15,
    gradYear: 2028,
    section: 'High School',
  },
  {
    id: 'wenxi-li',
    name: 'Wenxi Li',
    gender: 'Female',
    age: 11,
    gradYear: null,
    section: 'Middle School',
  },
  {
    id: 'arthas-limsakulwattana',
    name: 'Arthas Limsakulwattana',
    gender: 'Male',
    age: 9,
    gradYear: null,
    section: 'Elementary',
  },
  {
    id: 'laphon-manosuthisan',
    name: 'Laphon Manosuthisan',
    gender: 'Male',
    age: 15,
    gradYear: 2028,
    section: 'High School',
  },
  {
    id: 'erica-medyarova',
    name: 'Erica Medyarova',
    gender: 'Female',
    age: 15,
    gradYear: 2028,
    section: 'High School',
  },
  {
    id: 'palathip-panmai',
    name: 'Palathip Panmai',
    gender: 'Male',
    age: 11,
    gradYear: null,
    section: 'Middle School',
  },
  {
    id: 'ploynapas-pholsuwanchai',
    name: 'Ploynapas Pholsuwanchai',
    gender: 'Female',
    age: 11,
    gradYear: null,
    section: 'Middle School',
  },
  {
    id: 'thitibhorn-pronpanompong',
    name: 'Thitibhorn Pronpanompong',
    gender: 'Female',
    age: 11,
    gradYear: null,
    section: 'Middle School',
  },
  {
    id: 'tiarn-sripongtanakul',
    name: 'Tiarn Sripongtanakul',
    gender: 'Female',
    age: 16,
    gradYear: 2028,
    section: 'High School',
  },
  {
    id: 'tyler-srisumrid',
    name: 'Tyler Srisumrid',
    gender: 'Male',
    age: 12,
    gradYear: null,
    section: 'Middle School',
  },
  {
    id: 'virunpat-sriyanuwatkul',
    name: 'Virunpat Sriyanuwatkul',
    gender: 'Female',
    age: 16,
    gradYear: 2027,
    section: 'High School',
  },
  {
    id: 'kanyapak-tamonut',
    name: 'Kanyapak Tamonut',
    gender: 'Female',
    age: 13,
    gradYear: null,
    section: 'Middle School',
  },
  {
    id: 'pattadon-tamonut',
    name: 'Pattadon Tamonut',
    gender: 'Male',
    age: 10,
    gradYear: null,
    section: 'Elementary',
  },
  {
    id: 'abhikhun-tanchanpongs',
    name: 'Abhikhun Tanchanpongs',
    gender: 'Male',
    age: 16,
    gradYear: 2027,
    section: 'High School',
  },
  {
    id: 'punyapat-thepnumsommanus',
    name: 'Punyapat Thepnumsommanus',
    gender: 'Male',
    age: 17,
    gradYear: 2026,
    section: 'High School',
  },
  {
    id: 'narisara-tiranatvitayakul',
    name: 'Narisara Tiranatvitayakul',
    gender: 'Female',
    age: 12,
    gradYear: null,
    section: 'Middle School',
  },
  {
    id: 'techid-tongviseskul',
    name: 'Techid Tongviseskul',
    gender: 'Male',
    age: 17,
    gradYear: 2026,
    section: 'High School',
  },
  {
    id: 'peeravich-uea-amonvanish',
    name: 'Peeravich Uea-amonvanish',
    gender: 'Male',
    age: 11,
    gradYear: null,
    section: 'Middle School',
  },
  {
    id: 'andrew-vitayakul',
    name: 'Andrew Vitayakul',
    gender: 'Male',
    age: 13,
    gradYear: null,
    section: 'Middle School',
  },
  {
    id: 'bhat-wongtiraporn',
    name: 'Bhat Wongtiraporn',
    gender: 'Male',
    age: 14,
    gradYear: 2028,
    section: 'High School',
  },
  {
    id: 'wenran-xie',
    name: 'Wenran Xie',
    gender: 'Female',
    age: 12,
    gradYear: null,
    section: 'Middle School',
  },
  {
    id: 'vincent-yodpijit',
    name: 'Vincent Yodpijit',
    gender: 'Male',
    age: 10,
    gradYear: null,
    section: 'Elementary',
  },
  {
    id: 'qingzhi-zhang',
    name: 'Qingzhi Zhang',
    gender: 'Female',
    age: 8,
    gradYear: null,
    section: 'Elementary',
  },
];
