// src/lib/mockSwimmerResults.ts
//
// Individual race results for the Swimmer Profile page (§3.B), parsed from
// the 2025-2026 multi-meet results report via src/lib/parseResults.ts.
// Relay/leadoff rows already excluded at parse time. Used to derive both
// the personal-bests board and the most-recent-meet section — see
// src/lib/swimmerStats.ts.

import type { RaceResult } from './types';

export const mockSwimmerResults: RaceResult[] = [
  {
    swimmerId: 'akasya-ayturk',
    swimmerName: 'Akasya Ayturk',
    event: '25 Backstroke',
    time: '20.59S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: null,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'akasya-ayturk',
    swimmerName: 'Akasya Ayturk',
    event: '25 Butterfly',
    time: '17.66S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: null,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'akasya-ayturk',
    swimmerName: 'Akasya Ayturk',
    event: '100 Individual Medley',
    time: '1:29.62S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: null,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'yu-bo-chen',
    swimmerName: 'Yu Bo Chen',
    event: '50 Freestyle',
    time: null,
    noShow: true,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: null,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'yu-bo-chen',
    swimmerName: 'Yu Bo Chen',
    event: '50 Freestyle',
    time: '26.65S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 4,
    personalBestDiff: -2.65,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'yu-bo-chen',
    swimmerName: 'Yu Bo Chen',
    event: '100 Freestyle',
    time: '57.25S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 3,
    personalBestDiff: -9.16,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'yu-bo-chen',
    swimmerName: 'Yu Bo Chen',
    event: '50 Breaststroke',
    time: '33.62S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 3,
    personalBestDiff: -3.76,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'yu-bo-chen',
    swimmerName: 'Yu Bo Chen',
    event: '50 Butterfly',
    time: '28.07S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: -7.17,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'yu-bo-chen',
    swimmerName: 'Yu Bo Chen',
    event: '200 Individual Medley',
    time: '2:27.63S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 2,
    personalBestDiff: null,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'nattakit-choochaisengrat',
    swimmerName: 'Nattakit Choochaisengrat',
    event: '50 Freestyle',
    time: '29.65S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 8,
    personalBestDiff: -0.34,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'nattakit-choochaisengrat',
    swimmerName: 'Nattakit Choochaisengrat',
    event: '50 Freestyle',
    time: '30.31S',
    noShow: false,
    disqualified: false,
    exhibition: true,
    place: null,
    personalBestDiff: 0.66,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'nattakit-choochaisengrat',
    swimmerName: 'Nattakit Choochaisengrat',
    event: '100 Freestyle',
    time: '1:09.42S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 5,
    personalBestDiff: -1.05,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'nattakit-choochaisengrat',
    swimmerName: 'Nattakit Choochaisengrat',
    event: '100 Freestyle',
    time: '1:08.20S',
    noShow: false,
    disqualified: false,
    exhibition: true,
    place: null,
    personalBestDiff: -1.22,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'nattakit-choochaisengrat',
    swimmerName: 'Nattakit Choochaisengrat',
    event: '200 Freestyle',
    time: '2:44.94S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 9,
    personalBestDiff: null,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'nattakit-choochaisengrat',
    swimmerName: 'Nattakit Choochaisengrat',
    event: '100 Backstroke',
    time: '1:34.32S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 10,
    personalBestDiff: null,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'nattakit-choochaisengrat',
    swimmerName: 'Nattakit Choochaisengrat',
    event: '200 Backstroke',
    time: '3:25.08S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 7,
    personalBestDiff: null,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'matilde-cissna',
    swimmerName: 'Matilde Cissna',
    event: '100 Freestyle',
    time: '1:26.88S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: null,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'yunxi-gao',
    swimmerName: 'Yunxi Gao',
    event: '25 Freestyle',
    time: '33.13S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: null,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'yunxi-gao',
    swimmerName: 'Yunxi Gao',
    event: '25 Breaststroke',
    time: '33.29S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: null,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'ran-guo',
    swimmerName: 'Ran Guo',
    event: '50 Freestyle',
    time: '27.24S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: -0.37,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'ran-guo',
    swimmerName: 'Ran Guo',
    event: '100 Freestyle',
    time: '1:01.26S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: -0.45,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'ran-guo',
    swimmerName: 'Ran Guo',
    event: '200 Freestyle',
    time: '2:20.66S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: null,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'ran-guo',
    swimmerName: 'Ran Guo',
    event: '50 Breaststroke',
    time: '38.46S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: 1.57,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'ran-guo',
    swimmerName: 'Ran Guo',
    event: '50 Butterfly',
    time: '30.53S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: 0.5,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'ran-guo',
    swimmerName: 'Ran Guo',
    event: '50 Butterfly',
    time: '28.80S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: -1.23,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'ran-guo',
    swimmerName: 'Ran Guo',
    event: '100 Butterfly',
    time: '1:06.32S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: -2.95,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'ran-guo',
    swimmerName: 'Ran Guo',
    event: '100 Individual Medley',
    time: '1:09.80S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: null,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'ran-guo',
    swimmerName: 'Ran Guo',
    event: '200 Individual Medley',
    time: '2:34.31S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: 0.62,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'nanon-hanphanpong',
    swimmerName: 'Nanon Hanphanpong',
    event: '100 Freestyle',
    time: '1:12.24S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: -3.54,
    date: '1/31/2026',
    meetName: 'Eastern Bangkok Swim League U-14 Championship',
  },
  {
    swimmerId: 'nanon-hanphanpong',
    swimmerName: 'Nanon Hanphanpong',
    event: '200 Freestyle',
    time: '2:49.78S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: -5.68,
    date: '1/31/2026',
    meetName: 'Eastern Bangkok Swim League U-14 Championship',
  },
  {
    swimmerId: 'nanon-hanphanpong',
    swimmerName: 'Nanon Hanphanpong',
    event: '100 Individual Medley',
    time: '1:32.14S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: -2.46,
    date: '1/31/2026',
    meetName: 'Eastern Bangkok Swim League U-14 Championship',
  },
  {
    swimmerId: 'pornnapa-khangrang',
    swimmerName: 'Pornnapa Khangrang',
    event: '50 Backstroke',
    time: '59.67S',
    noShow: false,
    disqualified: false,
    exhibition: true,
    place: null,
    personalBestDiff: null,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'pornnapa-khangrang',
    swimmerName: 'Pornnapa Khangrang',
    event: '50 Breaststroke',
    time: '1:02.12S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 7,
    personalBestDiff: null,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'pornnapa-khangrang',
    swimmerName: 'Pornnapa Khangrang',
    event: '100 Breaststroke',
    time: '2:16.80S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 2,
    personalBestDiff: null,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'pornnapa-khangrang',
    swimmerName: 'Pornnapa Khangrang',
    event: '100 Breaststroke',
    time: '2:15.11S',
    noShow: false,
    disqualified: false,
    exhibition: true,
    place: null,
    personalBestDiff: -1.69,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'sion-kim',
    swimmerName: 'Sion Kim',
    event: '50 Freestyle',
    time: '45.24S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 6,
    personalBestDiff: -1.04,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'sion-kim',
    swimmerName: 'Sion Kim',
    event: '50 Freestyle',
    time: '42.60S',
    noShow: false,
    disqualified: false,
    exhibition: true,
    place: null,
    personalBestDiff: -2.64,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'sion-kim',
    swimmerName: 'Sion Kim',
    event: '100 Freestyle',
    time: '1:40.42S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 4,
    personalBestDiff: null,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'sion-kim',
    swimmerName: 'Sion Kim',
    event: '100 Freestyle',
    time: '1:34.89S',
    noShow: false,
    disqualified: false,
    exhibition: true,
    place: null,
    personalBestDiff: -5.53,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'sion-kim',
    swimmerName: 'Sion Kim',
    event: '50 Backstroke',
    time: '1:07.54S',
    noShow: false,
    disqualified: false,
    exhibition: true,
    place: null,
    personalBestDiff: -12.78,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'sion-kim',
    swimmerName: 'Sion Kim',
    event: '50 Breaststroke',
    time: '1:05.16S',
    noShow: false,
    disqualified: false,
    exhibition: true,
    place: null,
    personalBestDiff: null,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'sion-kim',
    swimmerName: 'Sion Kim',
    event: '50 Butterfly',
    time: '55.58S',
    noShow: false,
    disqualified: false,
    exhibition: true,
    place: null,
    personalBestDiff: null,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'varidrada-kithen',
    swimmerName: 'Varidrada Kithen',
    event: '50 Freestyle',
    time: '41.93S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 2,
    personalBestDiff: 2.37,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'varidrada-kithen',
    swimmerName: 'Varidrada Kithen',
    event: '50 Freestyle',
    time: '39.58S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 14,
    personalBestDiff: 0.02,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'varidrada-kithen',
    swimmerName: 'Varidrada Kithen',
    event: '200 Freestyle',
    time: '3:12.47S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 11,
    personalBestDiff: -9.78,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'varidrada-kithen',
    swimmerName: 'Varidrada Kithen',
    event: '50 Backstroke',
    time: '55.43S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 3,
    personalBestDiff: 5.44,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'varidrada-kithen',
    swimmerName: 'Varidrada Kithen',
    event: '50 Backstroke',
    time: '53.85S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 15,
    personalBestDiff: 3.86,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'varidrada-kithen',
    swimmerName: 'Varidrada Kithen',
    event: '50 Breaststroke',
    time: '57.11S',
    noShow: false,
    disqualified: false,
    exhibition: true,
    place: null,
    personalBestDiff: 1.8,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'varidrada-kithen',
    swimmerName: 'Varidrada Kithen',
    event: '50 Butterfly',
    time: '49.50S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 14,
    personalBestDiff: null,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'soo-yeon-kwon',
    swimmerName: 'Soo Yeon Kwon',
    event: '50 Freestyle',
    time: '43.60S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 4,
    personalBestDiff: -1.12,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'soo-yeon-kwon',
    swimmerName: 'Soo Yeon Kwon',
    event: '50 Freestyle',
    time: '44.84S',
    noShow: false,
    disqualified: false,
    exhibition: true,
    place: null,
    personalBestDiff: 1.24,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'soo-yeon-kwon',
    swimmerName: 'Soo Yeon Kwon',
    event: '100 Freestyle',
    time: '1:46.44S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 6,
    personalBestDiff: -11.34,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'soo-yeon-kwon',
    swimmerName: 'Soo Yeon Kwon',
    event: '100 Freestyle',
    time: '1:49.68S',
    noShow: false,
    disqualified: false,
    exhibition: true,
    place: null,
    personalBestDiff: 3.24,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'soo-yeon-kwon',
    swimmerName: 'Soo Yeon Kwon',
    event: '50 Breaststroke',
    time: '1:00.60S',
    noShow: false,
    disqualified: true,
    exhibition: true,
    place: null,
    personalBestDiff: null,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'soo-yeon-kwon',
    swimmerName: 'Soo Yeon Kwon',
    event: '50 Butterfly',
    time: '1:04.37S',
    noShow: false,
    disqualified: false,
    exhibition: true,
    place: null,
    personalBestDiff: null,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'trevin-laduke',
    swimmerName: 'Trevin LaDuke',
    event: '25 Freestyle',
    time: '17.26S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: -2.12,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'trevin-laduke',
    swimmerName: 'Trevin LaDuke',
    event: '50 Freestyle',
    time: '39.97S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: -1.16,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'trevin-laduke',
    swimmerName: 'Trevin LaDuke',
    event: '100 Freestyle',
    time: '1:27.11S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 6,
    personalBestDiff: -1.24,
    date: '1/31/2026',
    meetName: 'Eastern Bangkok Swim League U-14 Championship',
  },
  {
    swimmerId: 'trevin-laduke',
    swimmerName: 'Trevin LaDuke',
    event: '200 Freestyle',
    time: '3:08.72S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 2,
    personalBestDiff: -1.64,
    date: '1/31/2026',
    meetName: 'Eastern Bangkok Swim League U-14 Championship',
  },
  {
    swimmerId: 'trevin-laduke',
    swimmerName: 'Trevin LaDuke',
    event: '25 Backstroke',
    time: '22.04S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: -4.22,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'trevin-laduke',
    swimmerName: 'Trevin LaDuke',
    event: '25 Breaststroke',
    time: '24.31S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: -7.78,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'trevin-laduke',
    swimmerName: 'Trevin LaDuke',
    event: '100 Breaststroke',
    time: '1:57.86S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 3,
    personalBestDiff: -21.79,
    date: '1/31/2026',
    meetName: 'Eastern Bangkok Swim League U-14 Championship',
  },
  {
    swimmerId: 'abigail-leighton',
    swimmerName: 'Abigail Leighton',
    event: '50 Freestyle',
    time: '37.80S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: null,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'abigail-leighton',
    swimmerName: 'Abigail Leighton',
    event: '100 Freestyle',
    time: '1:25.75S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 2,
    personalBestDiff: null,
    date: '1/31/2026',
    meetName: 'Eastern Bangkok Swim League U-14 Championship',
  },
  {
    swimmerId: 'abigail-leighton',
    swimmerName: 'Abigail Leighton',
    event: '200 Freestyle',
    time: '3:02.52S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 2,
    personalBestDiff: null,
    date: '1/31/2026',
    meetName: 'Eastern Bangkok Swim League U-14 Championship',
  },
  {
    swimmerId: 'abigail-leighton',
    swimmerName: 'Abigail Leighton',
    event: '100 Individual Medley',
    time: '1:39.94S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 2,
    personalBestDiff: null,
    date: '1/31/2026',
    meetName: 'Eastern Bangkok Swim League U-14 Championship',
  },
  {
    swimmerId: 'eleanor-leighton',
    swimmerName: 'Eleanor Leighton',
    event: '100 Freestyle',
    time: '1:19.21S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: null,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'eleanor-leighton',
    swimmerName: 'Eleanor Leighton',
    event: '100 Freestyle',
    time: '1:08.56S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 4,
    personalBestDiff: -10.65,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'eleanor-leighton',
    swimmerName: 'Eleanor Leighton',
    event: '400 Freestyle',
    time: '5:24.36S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 4,
    personalBestDiff: null,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'eleanor-leighton',
    swimmerName: 'Eleanor Leighton',
    event: '50 Backstroke',
    time: '36.32S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 6,
    personalBestDiff: -1.54,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'eleanor-leighton',
    swimmerName: 'Eleanor Leighton',
    event: '100 Backstroke',
    time: '1:28.04S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: 5.99,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'eleanor-leighton',
    swimmerName: 'Eleanor Leighton',
    event: '100 Backstroke',
    time: '1:19.84S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 4,
    personalBestDiff: -2.21,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'eleanor-leighton',
    swimmerName: 'Eleanor Leighton',
    event: '200 Backstroke',
    time: '2:52.07S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 5,
    personalBestDiff: null,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'wenxi-li',
    swimmerName: 'Wenxi Li',
    event: '25 Freestyle',
    time: '22.09S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: null,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'arthas-limsakulwattana',
    swimmerName: 'Arthas Limsakulwattana',
    event: '25 Butterfly',
    time: '35.43S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: null,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'laphon-manosuthisan',
    swimmerName: 'Laphon Manosuthisan',
    event: '50 Freestyle',
    time: '29.12S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 7,
    personalBestDiff: 0.49,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'laphon-manosuthisan',
    swimmerName: 'Laphon Manosuthisan',
    event: '50 Freestyle',
    time: '28.06S',
    noShow: false,
    disqualified: false,
    exhibition: true,
    place: null,
    personalBestDiff: -0.57,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'laphon-manosuthisan',
    swimmerName: 'Laphon Manosuthisan',
    event: '200 Freestyle',
    time: '2:35.93S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 7,
    personalBestDiff: 1.61,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'laphon-manosuthisan',
    swimmerName: 'Laphon Manosuthisan',
    event: '50 Backstroke',
    time: '34.04S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 4,
    personalBestDiff: -5.02,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'laphon-manosuthisan',
    swimmerName: 'Laphon Manosuthisan',
    event: '100 Backstroke',
    time: '1:22.52S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 2,
    personalBestDiff: 4.33,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'laphon-manosuthisan',
    swimmerName: 'Laphon Manosuthisan',
    event: '100 Backstroke',
    time: '1:17.87S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 5,
    personalBestDiff: -0.32,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'laphon-manosuthisan',
    swimmerName: 'Laphon Manosuthisan',
    event: '100 Breaststroke',
    time: '1:34.86S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 2,
    personalBestDiff: 8.65,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'laphon-manosuthisan',
    swimmerName: 'Laphon Manosuthisan',
    event: '100 Butterfly',
    time: '1:16.17S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 5,
    personalBestDiff: -6.38,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'erica-medyarova',
    swimmerName: 'Erica Medyarova',
    event: '100 Freestyle',
    time: '1:26.41S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 2,
    personalBestDiff: -7.67,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'erica-medyarova',
    swimmerName: 'Erica Medyarova',
    event: '100 Freestyle',
    time: '1:24.67S',
    noShow: false,
    disqualified: false,
    exhibition: true,
    place: null,
    personalBestDiff: -1.74,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'erica-medyarova',
    swimmerName: 'Erica Medyarova',
    event: '400 Freestyle',
    time: '6:45.53S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 10,
    personalBestDiff: null,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'erica-medyarova',
    swimmerName: 'Erica Medyarova',
    event: '100 Backstroke',
    time: '1:42.85S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 2,
    personalBestDiff: -0.62,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'erica-medyarova',
    swimmerName: 'Erica Medyarova',
    event: '100 Backstroke',
    time: '1:38.63S',
    noShow: false,
    disqualified: false,
    exhibition: true,
    place: null,
    personalBestDiff: -4.22,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'erica-medyarova',
    swimmerName: 'Erica Medyarova',
    event: '50 Breaststroke',
    time: '51.10S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 13,
    personalBestDiff: 0.74,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'erica-medyarova',
    swimmerName: 'Erica Medyarova',
    event: '100 Individual Medley',
    time: '1:39.33S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 11,
    personalBestDiff: null,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'palathip-panmai',
    swimmerName: 'Palathip Panmai',
    event: '50 Freestyle',
    time: '39.67S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 4,
    personalBestDiff: null,
    date: '1/31/2026',
    meetName: 'Eastern Bangkok Swim League U-14 Championship',
  },
  {
    swimmerId: 'palathip-panmai',
    swimmerName: 'Palathip Panmai',
    event: '50 Breaststroke',
    time: '50.92S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 6,
    personalBestDiff: null,
    date: '1/31/2026',
    meetName: 'Eastern Bangkok Swim League U-14 Championship',
  },
  {
    swimmerId: 'palathip-panmai',
    swimmerName: 'Palathip Panmai',
    event: '50 Butterfly',
    time: '52.43S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: null,
    date: '1/31/2026',
    meetName: 'Eastern Bangkok Swim League U-14 Championship',
  },
  {
    swimmerId: 'ploynapas-pholsuwanchai',
    swimmerName: 'Ploynapas Pholsuwanchai',
    event: '25 Backstroke',
    time: '23.66S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: -6.4,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'ploynapas-pholsuwanchai',
    swimmerName: 'Ploynapas Pholsuwanchai',
    event: '50 Butterfly',
    time: '45.72S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: 0.53,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'ploynapas-pholsuwanchai',
    swimmerName: 'Ploynapas Pholsuwanchai',
    event: '100 Individual Medley',
    time: '1:39.82S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: -8.97,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'thitibhorn-pronpanompong',
    swimmerName: 'Thitibhorn Pronpanompong',
    event: '50 Backstroke',
    time: '54.98S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: 26.49,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'thitibhorn-pronpanompong',
    swimmerName: 'Thitibhorn Pronpanompong',
    event: '50 Breaststroke',
    time: '57.82S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: 1.63,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'tiarn-sripongtanakul',
    swimmerName: 'Tiarn Sripongtanakul',
    event: '50 Freestyle',
    time: '32.81S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: -0.06,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'tiarn-sripongtanakul',
    swimmerName: 'Tiarn Sripongtanakul',
    event: '100 Backstroke',
    time: '1:30.58S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 9,
    personalBestDiff: null,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'tiarn-sripongtanakul',
    swimmerName: 'Tiarn Sripongtanakul',
    event: '50 Breaststroke',
    time: '43.31S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 4,
    personalBestDiff: -0.24,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'tiarn-sripongtanakul',
    swimmerName: 'Tiarn Sripongtanakul',
    event: '100 Breaststroke',
    time: '1:34.99S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 5,
    personalBestDiff: 0.98,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'tiarn-sripongtanakul',
    swimmerName: 'Tiarn Sripongtanakul',
    event: '200 Breaststroke',
    time: '3:32.22S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 6,
    personalBestDiff: null,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'tiarn-sripongtanakul',
    swimmerName: 'Tiarn Sripongtanakul',
    event: '100 Individual Medley',
    time: '1:26.50S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 6,
    personalBestDiff: 2.3,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'tyler-srisumrid',
    swimmerName: 'Tyler Srisumrid',
    event: '100 Freestyle',
    time: '1:32.25S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 8,
    personalBestDiff: null,
    date: '1/31/2026',
    meetName: 'Eastern Bangkok Swim League U-14 Championship',
  },
  {
    swimmerId: 'tyler-srisumrid',
    swimmerName: 'Tyler Srisumrid',
    event: '50 Breaststroke',
    time: '53.84S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 8,
    personalBestDiff: null,
    date: '1/31/2026',
    meetName: 'Eastern Bangkok Swim League U-14 Championship',
  },
  {
    swimmerId: 'tyler-srisumrid',
    swimmerName: 'Tyler Srisumrid',
    event: '100 Individual Medley',
    time: '1:48.98S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 4,
    personalBestDiff: null,
    date: '1/31/2026',
    meetName: 'Eastern Bangkok Swim League U-14 Championship',
  },
  {
    swimmerId: 'virunpat-sriyanuwatkul',
    swimmerName: 'Virunpat Sriyanuwatkul',
    event: '50 Freestyle',
    time: '39.63S',
    noShow: false,
    disqualified: false,
    exhibition: true,
    place: null,
    personalBestDiff: -0.71,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'virunpat-sriyanuwatkul',
    swimmerName: 'Virunpat Sriyanuwatkul',
    event: '50 Backstroke',
    time: '50.30S',
    noShow: false,
    disqualified: false,
    exhibition: true,
    place: null,
    personalBestDiff: -1.07,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'virunpat-sriyanuwatkul',
    swimmerName: 'Virunpat Sriyanuwatkul',
    event: '50 Breaststroke',
    time: '51.80S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 3,
    personalBestDiff: 1.3,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'virunpat-sriyanuwatkul',
    swimmerName: 'Virunpat Sriyanuwatkul',
    event: '50 Breaststroke',
    time: '50.40S',
    noShow: false,
    disqualified: false,
    exhibition: true,
    place: null,
    personalBestDiff: -0.1,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'virunpat-sriyanuwatkul',
    swimmerName: 'Virunpat Sriyanuwatkul',
    event: '100 Breaststroke',
    time: '2:00.40S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: 7.26,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'virunpat-sriyanuwatkul',
    swimmerName: 'Virunpat Sriyanuwatkul',
    event: '100 Breaststroke',
    time: '1:50.33S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 13,
    personalBestDiff: -2.81,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'virunpat-sriyanuwatkul',
    swimmerName: 'Virunpat Sriyanuwatkul',
    event: '50 Butterfly',
    time: '54.72S',
    noShow: false,
    disqualified: false,
    exhibition: true,
    place: null,
    personalBestDiff: -2.96,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'kanyapak-tamonut',
    swimmerName: 'Kanyapak Tamonut',
    event: '25 Freestyle',
    time: '14.01S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: -3,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'kanyapak-tamonut',
    swimmerName: 'Kanyapak Tamonut',
    event: '50 Freestyle',
    time: '31.15S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: -0.48,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'kanyapak-tamonut',
    swimmerName: 'Kanyapak Tamonut',
    event: '100 Freestyle',
    time: '1:07.67S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: -3.14,
    date: '1/31/2026',
    meetName: 'Eastern Bangkok Swim League U-14 Championship',
  },
  {
    swimmerId: 'kanyapak-tamonut',
    swimmerName: 'Kanyapak Tamonut',
    event: '100 Freestyle',
    time: '1:08.67S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: 1,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'kanyapak-tamonut',
    swimmerName: 'Kanyapak Tamonut',
    event: '100 Backstroke',
    time: '1:18.62S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: -6.63,
    date: '1/31/2026',
    meetName: 'Eastern Bangkok Swim League U-14 Championship',
  },
  {
    swimmerId: 'kanyapak-tamonut',
    swimmerName: 'Kanyapak Tamonut',
    event: '25 Butterfly',
    time: '14.88S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: -3.38,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'kanyapak-tamonut',
    swimmerName: 'Kanyapak Tamonut',
    event: '200 Individual Medley',
    time: '2:50.02S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: -11.86,
    date: '1/31/2026',
    meetName: 'Eastern Bangkok Swim League U-14 Championship',
  },
  {
    swimmerId: 'pattadon-tamonut',
    swimmerName: 'Pattadon Tamonut',
    event: '50 Freestyle',
    time: '40.84S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: 1.61,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'pattadon-tamonut',
    swimmerName: 'Pattadon Tamonut',
    event: '50 Breaststroke',
    time: '57.32S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: 1.98,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'pattadon-tamonut',
    swimmerName: 'Pattadon Tamonut',
    event: '25 Butterfly',
    time: '22.61S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: null,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'abhikhun-tanchanpongs',
    swimmerName: 'Abhikhun Tanchanpongs',
    event: '50 Freestyle',
    time: '29.94S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: -0.57,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'abhikhun-tanchanpongs',
    swimmerName: 'Abhikhun Tanchanpongs',
    event: '50 Freestyle',
    time: '30.23S',
    noShow: false,
    disqualified: false,
    exhibition: true,
    place: null,
    personalBestDiff: 0.29,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'abhikhun-tanchanpongs',
    swimmerName: 'Abhikhun Tanchanpongs',
    event: '100 Freestyle',
    time: '1:11.08S',
    noShow: false,
    disqualified: false,
    exhibition: true,
    place: null,
    personalBestDiff: -5.29,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'abhikhun-tanchanpongs',
    swimmerName: 'Abhikhun Tanchanpongs',
    event: '50 Breaststroke',
    time: '41.09S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 6,
    personalBestDiff: 2.27,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'abhikhun-tanchanpongs',
    swimmerName: 'Abhikhun Tanchanpongs',
    event: '50 Breaststroke',
    time: '40.00S',
    noShow: false,
    disqualified: false,
    exhibition: true,
    place: null,
    personalBestDiff: 1.18,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'abhikhun-tanchanpongs',
    swimmerName: 'Abhikhun Tanchanpongs',
    event: '100 Breaststroke',
    time: '1:38.44S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 11,
    personalBestDiff: -3.43,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'abhikhun-tanchanpongs',
    swimmerName: 'Abhikhun Tanchanpongs',
    event: '50 Butterfly',
    time: '36.22S',
    noShow: false,
    disqualified: false,
    exhibition: true,
    place: null,
    personalBestDiff: 0.42,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'punyapat-thepnumsommanus',
    swimmerName: 'Punyapat Thepnumsommanus',
    event: '50 Freestyle',
    time: '26.95S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 3,
    personalBestDiff: -1.71,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'punyapat-thepnumsommanus',
    swimmerName: 'Punyapat Thepnumsommanus',
    event: '50 Freestyle',
    time: '26.60S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 3,
    personalBestDiff: -0.35,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'punyapat-thepnumsommanus',
    swimmerName: 'Punyapat Thepnumsommanus',
    event: '100 Freestyle',
    time: '1:00.72S',
    noShow: false,
    disqualified: false,
    exhibition: true,
    place: null,
    personalBestDiff: null,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'punyapat-thepnumsommanus',
    swimmerName: 'Punyapat Thepnumsommanus',
    event: '50 Breaststroke',
    time: '33.84S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 2,
    personalBestDiff: -2.32,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'punyapat-thepnumsommanus',
    swimmerName: 'Punyapat Thepnumsommanus',
    event: '50 Breaststroke',
    time: '32.84S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 2,
    personalBestDiff: -1,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'punyapat-thepnumsommanus',
    swimmerName: 'Punyapat Thepnumsommanus',
    event: '50 Butterfly',
    time: '29.51S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 3,
    personalBestDiff: null,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'punyapat-thepnumsommanus',
    swimmerName: 'Punyapat Thepnumsommanus',
    event: '100 Individual Medley',
    time: '1:07.45S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 3,
    personalBestDiff: -4.3,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'narisara-tiranatvitayakul',
    swimmerName: 'Narisara Tiranatvitayakul',
    event: '25 Freestyle',
    time: '14.87S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: -2.07,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'narisara-tiranatvitayakul',
    swimmerName: 'Narisara Tiranatvitayakul',
    event: '200 Freestyle',
    time: '2:37.18S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: -2.33,
    date: '1/31/2026',
    meetName: 'Eastern Bangkok Swim League U-14 Championship',
  },
  {
    swimmerId: 'narisara-tiranatvitayakul',
    swimmerName: 'Narisara Tiranatvitayakul',
    event: '25 Backstroke',
    time: '18.02S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: -2.43,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'narisara-tiranatvitayakul',
    swimmerName: 'Narisara Tiranatvitayakul',
    event: '100 Backstroke',
    time: '1:19.87S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 2,
    personalBestDiff: -3.64,
    date: '1/31/2026',
    meetName: 'Eastern Bangkok Swim League U-14 Championship',
  },
  {
    swimmerId: 'narisara-tiranatvitayakul',
    swimmerName: 'Narisara Tiranatvitayakul',
    event: '25 Butterfly',
    time: '15.31S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: -3.06,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'narisara-tiranatvitayakul',
    swimmerName: 'Narisara Tiranatvitayakul',
    event: '100 Individual Medley',
    time: '1:20.28S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: -3.04,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'narisara-tiranatvitayakul',
    swimmerName: 'Narisara Tiranatvitayakul',
    event: '200 Individual Medley',
    time: '2:50.34S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 2,
    personalBestDiff: -5.65,
    date: '1/31/2026',
    meetName: 'Eastern Bangkok Swim League U-14 Championship',
  },
  {
    swimmerId: 'techid-tongviseskul',
    swimmerName: 'Techid Tongviseskul',
    event: '50 Freestyle',
    time: '25.38S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: null,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'techid-tongviseskul',
    swimmerName: 'Techid Tongviseskul',
    event: '100 Freestyle',
    time: '55.60S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: null,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'techid-tongviseskul',
    swimmerName: 'Techid Tongviseskul',
    event: '400 Freestyle',
    time: '4:13.66S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: null,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'techid-tongviseskul',
    swimmerName: 'Techid Tongviseskul',
    event: '50 Breaststroke',
    time: '32.03S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: null,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'techid-tongviseskul',
    swimmerName: 'Techid Tongviseskul',
    event: '100 Breaststroke',
    time: '1:08.85S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: null,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'techid-tongviseskul',
    swimmerName: 'Techid Tongviseskul',
    event: '100 Breaststroke',
    time: '1:04.68S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: -4.17,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'techid-tongviseskul',
    swimmerName: 'Techid Tongviseskul',
    event: '200 Breaststroke',
    time: '2:20.39S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: null,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'techid-tongviseskul',
    swimmerName: 'Techid Tongviseskul',
    event: '50 Butterfly',
    time: '27.23S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: null,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'techid-tongviseskul',
    swimmerName: 'Techid Tongviseskul',
    event: '200 Individual Medley',
    time: '2:09.88S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: null,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'techid-tongviseskul',
    swimmerName: 'Techid Tongviseskul',
    event: '400 Individual Medley',
    time: '4:36.52S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: null,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'peeravich-uea-amonvanish',
    swimmerName: 'Peeravich Uea-amonvanish',
    event: '25 Freestyle',
    time: '18.13S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: -0.22,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'peeravich-uea-amonvanish',
    swimmerName: 'Peeravich Uea-amonvanish',
    event: '50 Backstroke',
    time: '51.57S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: -4.61,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'peeravich-uea-amonvanish',
    swimmerName: 'Peeravich Uea-amonvanish',
    event: '50 Breaststroke',
    time: '1:00.98S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: -1.02,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'andrew-vitayakul',
    swimmerName: 'Andrew Vitayakul',
    event: '100 Freestyle',
    time: '1:21.32S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 3,
    personalBestDiff: -6.24,
    date: '1/31/2026',
    meetName: 'Eastern Bangkok Swim League U-14 Championship',
  },
  {
    swimmerId: 'andrew-vitayakul',
    swimmerName: 'Andrew Vitayakul',
    event: '50 Breaststroke',
    time: '45.34S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 2,
    personalBestDiff: -1.84,
    date: '1/31/2026',
    meetName: 'Eastern Bangkok Swim League U-14 Championship',
  },
  {
    swimmerId: 'andrew-vitayakul',
    swimmerName: 'Andrew Vitayakul',
    event: '200 Individual Medley',
    time: '3:28.72S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 1,
    personalBestDiff: -16.22,
    date: '1/31/2026',
    meetName: 'Eastern Bangkok Swim League U-14 Championship',
  },
  {
    swimmerId: 'bhat-wongtiraporn',
    swimmerName: 'Bhat Wongtiraporn',
    event: '50 Freestyle',
    time: '29.00S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 6,
    personalBestDiff: null,
    date: '9/30/2025',
    meetName: 'RIS @ ICS HS Sep 2025',
  },
  {
    swimmerId: 'bhat-wongtiraporn',
    swimmerName: 'Bhat Wongtiraporn',
    event: '50 Freestyle',
    time: '28.71S',
    noShow: false,
    disqualified: false,
    exhibition: true,
    place: null,
    personalBestDiff: -0.29,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'bhat-wongtiraporn',
    swimmerName: 'Bhat Wongtiraporn',
    event: '100 Freestyle',
    time: '1:06.91S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 5,
    personalBestDiff: null,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'bhat-wongtiraporn',
    swimmerName: 'Bhat Wongtiraporn',
    event: '50 Backstroke',
    time: '35.21S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 6,
    personalBestDiff: null,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'bhat-wongtiraporn',
    swimmerName: 'Bhat Wongtiraporn',
    event: '50 Breaststroke',
    time: '38.38S',
    noShow: false,
    disqualified: false,
    exhibition: true,
    place: null,
    personalBestDiff: null,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'bhat-wongtiraporn',
    swimmerName: 'Bhat Wongtiraporn',
    event: '100 Individual Medley',
    time: '1:15.96S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 7,
    personalBestDiff: null,
    date: '10/30/2025',
    meetName: 'ACSC ICS (Bangkok) 2025',
  },
  {
    swimmerId: 'wenran-xie',
    swimmerName: 'Wenran Xie',
    event: '50 Freestyle',
    time: '46.86S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 7,
    personalBestDiff: null,
    date: '1/31/2026',
    meetName: 'Eastern Bangkok Swim League U-14 Championship',
  },
  {
    swimmerId: 'wenran-xie',
    swimmerName: 'Wenran Xie',
    event: '50 Freestyle',
    time: '57.67S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: 10.81,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'wenran-xie',
    swimmerName: 'Wenran Xie',
    event: '50 Backstroke',
    time: '1:07.59S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: 6,
    personalBestDiff: null,
    date: '1/31/2026',
    meetName: 'Eastern Bangkok Swim League U-14 Championship',
  },
  {
    swimmerId: 'wenran-xie',
    swimmerName: 'Wenran Xie',
    event: '25 Breaststroke',
    time: '36.35S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: null,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'vincent-yodpijit',
    swimmerName: 'Vincent Yodpijit',
    event: '25 Freestyle',
    time: '16.12S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: -0.91,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'vincent-yodpijit',
    swimmerName: 'Vincent Yodpijit',
    event: '50 Freestyle',
    time: '38.20S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: -0.75,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'vincent-yodpijit',
    swimmerName: 'Vincent Yodpijit',
    event: '25 Backstroke',
    time: '22.65S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: 0.97,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'vincent-yodpijit',
    swimmerName: 'Vincent Yodpijit',
    event: '25 Breaststroke',
    time: '21.13S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: -1.69,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'qingzhi-zhang',
    swimmerName: 'Qingzhi Zhang',
    event: '25 Freestyle',
    time: '23.30S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: null,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'qingzhi-zhang',
    swimmerName: 'Qingzhi Zhang',
    event: '50 Freestyle',
    time: '1:02.37S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: null,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'qingzhi-zhang',
    swimmerName: 'Qingzhi Zhang',
    event: '25 Backstroke',
    time: '29.86S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: null,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'qingzhi-zhang',
    swimmerName: 'Qingzhi Zhang',
    event: '25 Breaststroke',
    time: '32.05S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: null,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
  {
    swimmerId: 'qingzhi-zhang',
    swimmerName: 'Qingzhi Zhang',
    event: '50 Breaststroke',
    time: '1:14.88S',
    noShow: false,
    disqualified: false,
    exhibition: false,
    place: null,
    personalBestDiff: null,
    date: '3/18/2026',
    meetName: 'RAS @ ICS',
  },
];
